apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mediawikis.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: Mediawiki
    listKind: MediawikiList
    plural: mediawikis
    singular: mediawiki
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
