apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mediawiki-operator
  template:
    metadata:
      labels:
        name: mediawiki-operator
    spec:
      serviceAccountName: mediawiki-operator
      containers:
        - name: mediawiki-operator
          # Replace this with the built image name
          image: docker.io/danclark/mediawiki-operator:v0.0.1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mediawiki-operator"
